### PR TITLE
[Feature] - Improve ceasefire side relations

### PR DESCRIPTION
**Pull request by Cre8or**
### Pull Request Description
**When merged this pull request will:**
- Enforce ceasefires on AI units by setting side relations

### Release Notes
Previously, ceasefires were partially enforced by using `setCaptive` on players. This had the side effect of tampering with player side affiliations (some players would be stuck on the civilian side), and it didn't affect AI-on-AI relations.
This new method uses global side relations (using `setFriend`) to stop AI hostilities altogether for the duration of the ceasefire. Once terminated, the previous side relations are restored.

## IMPORTANT

- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [x] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Review by dgibso29 — DISMISSED** [review]
Looks good to me. Good way to solve the issue. Thanks Cre.

**Review by dgibso29 — DISMISSED** [review]

**Review by Bubbus — DISMISSED** [review]
its good

**Comment by Cre8or** [comment]
Minor update to fix an error on the first execution of the server script. Also fixed the casing of a variable name.

**EDIT:** I'm aware the global variable `cafe_ceasefire_active` is already declared inside `init_component`, but it felt right to add it regardless as we might be calling the ceasefire function ahead of module initialisation in the future. This way, the declaration is handled by the file that uses it first.

**Comment by Bubbus** [comment]
serves me right for approving code based on just reading the diff lol

**Comment by dgibso29** [comment]
> serves me right for approving code based on just reading the diff lol

Same... The workflow is supposed to be server test before approval I suppose..

**Review by Bubbus — APPROVED** [review]
its good tho

**Pull request merged**
