### PR TITLE
[Feature] Gearscript item macros

### PR DESCRIPTION
**Pull request by Bubbus**
### Pull Request Description
**When merged this pull request will:**
Add the following commands for use in gearscript files:

```
ADD_ITEM_TO_UNIFORM(UNIT_NAME,"Item Name");
ADD_ITEMS_TO_UNIFORM(UNIT_NAME,"Item Name",AMOUNT);

ADD_ITEM_TO_VEST(UNIT_NAME,"Item Name");
ADD_ITEMS_TO_VEST(UNIT_NAME,"Item Name",AMOUNT);

ADD_ITEM_TO_BACKPACK(UNIT_NAME,"Item Name");
ADD_ITEMS_TO_BACKPACK(UNIT_NAME,"Item Name",AMOUNT);

REMOVE_ITEM_FROM_LOADOUT(UNIT_NAME,"Item Name");

ADD_MAP(UNIT_NAME);
REMOVE_MAP(UNIT_NAME);

ADD_GPS(UNIT_NAME);
ADD_TERMINAL(UNIT_NAME,"Item Name");
REMOVE_TERMINAL(UNIT_NAME);

ADD_COMPASS(UNIT_NAME);
REMOVE_COMPASS(UNIT_NAME);

ADD_WATCH(UNIT_NAME);
ADD_WATCH_ITEM(UNIT_NAME,"Item Name");
REMOVE_WATCH(UNIT_NAME);

ADD_NVG(UNIT_NAME,"Item Name");
REMOVE_NVG(UNIT_NAME);
```
These operate upon loadouts at mission start, so they add load at mission start but not mid-mission (when spawning units).

Tested a little bit in the mission editor, locally.

### Release Notes
_Added new commands for use in Gearscript.  These commands allow you to add gear to units without needing to bring them back into ACE Arsenal.  Useful for when you've forgotten an item etc.  For more information, see the `gearscript_readme.txt` in the latest version of the framework._

### CODE REVIEW

**Comment by Bubbus** [comment]
Related to #32.

**Review by dgibso29 — APPROVED** [review]
Nice additions. Looks good to me and works well.

I'm not good enough at SQF to comment on code quality, but nothing sticks out all the same.

Approved!

**Comment by dgibso29** [comment]
@Bubbus Any reason this can't be merged?

**Comment by Bubbus** [comment]
Not really, that's all the macros I personally need for now.  Any others like "Add bandages" etc can come when requested.

**Comment by dgibso29** [comment]
> Not really, that's all the macros I personally need for now. Any others like "Add bandages" etc can come when requested.

Cool. I'll merge this in but I am used to a flow in which the creator of a PR then merges it once approved (I am not married to this idea, just unsure what your expectation is in that area)

**Pull request merged**
