### PR TITLE
[Hotfix] Fixed side conditionals

### PR DESCRIPTION
**Pull request by Cre8or**
### Pull Request Description
**When merged this pull request will:**
- Modify side checks to run on groups rather than units (fixes edge cases with captivity; including incorrect ACRE2 language assignments)
- Modify the ceasefire component to delay the safestart until after the briefing
- Remove a debug print in one of the mission endings

### Release Notes
Hotfix in response to today's public framework beta playtest.

## IMPORTANT

- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [x] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Review by dgibso29 — DISMISSED** [review]
Good fix is good

**Review by Bubbus — DISMISSED** [review]
its good

its good tho

**Review by Joecuronium — APPROVED** [review]
Don't see any issues with this, LGTM

**Review by dgibso29 — APPROVED** [review]
Looks good. Merge it in & we'll test it today.

**Pull request merged**
