### PR TITLE
[Feature] - Add ACE actions to loadout lockers

### LINKED ISSUE #170: [Feature Request] Add ACE actions to the loadout locker.
**Is your feature request related to a problem? Please describe.**
Some people don't know the locker is a scroll action thing, so may as well add ACE actions too.

**Describe the solution you'd like**
add ACE actions too

**Why is this this best way to solve the problem?**
It's what they try first.

**Additional context**
👷‍♂️

### PR DESCRIPTION
**Pull request by Cre8or**
### Pull Request Description
**When merged this pull request will:**
- Add ACE actions to the loadout locker
- Automatically register loadout lockers as Zeus editable objects when spawned (QoL)
- Fix loadout locker bags not being deleted alongside their locker

### Release Notes
Loadout lockers now have ACE actions to take loadouts, alongside the regular vanilla actions.

## IMPORTANT

- [x] Testing has been completed as neccessary, depending on the nature & impact of the changes.
- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [x] If the contribution affects [the wiki](https://github.com/CombinedArmsGaming/CAFE3/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/CombinedArmsGaming/CAFE3/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

Closes #170.

### CODE REVIEW

**Review by dgibso29 — DISMISSED** [review]

**Review by Bubbus — DISMISSED** [review]
Nice, ty for surrounding fixes/changes too.

**Comment by Cre8or** [comment]
Turns out `allowFunctionsRecompile` does not care whether it's used in singleplayer or multiplayer.

The new restriction blocks it outside of 3DEN previews. This allows for the feature to be used in singleplayer (as originally intended), while disallowing it in hosted multiplayer environment (our normal use case). However, it does not disallow it from 3DEN multiplayer preview - something that I've thought about for quite a bit. We don't normally (read: *never*) host missions from client-hosted 3DEN preview, but if we were to, I suspect this feature might be useful, as I don't expect this to be done with a full multiplayer lobby. Thoughts on this?

**Review by dgibso29 — APPROVED** [review]
image

**Review by Bubbus — APPROVED** [review]
smash that like button

**Pull request merged**
