### PR TITLE
[Feature] - Add Ceasefire component, remove SafeStart/SafeEnd components

### LINKED ISSUE #59: [Feature] Safestart: RESTARTED
Safestart doesn't work and hasn't for a long time now.  The fact remains that it's supposed to be a feature we have though.  It was initially disabled by me a couple years ago because it was broken and I didn't know how to fix it, but that's probably not the case anymore.

- [x] Fix safestart and return it to its old feature set.
- [x] See if there's a better way to message to players how much time is left in safestart.  
- [ ] If players are not made invulnerable during safestart, make sure they get this.  In case they decide to jump out of buildings or climb under tanks or w/e.
- [ ] From memory, safestart wouldn't affect AI which sometimes lead to awkward situations - rare but not never.  See how easy it is to disable AI whenever safestart is on.  

Side thoughts:
* If there's a good way to display a counting-down timer on the screen then we should do that for the 2nd criterion, because we can reuse that functionality later on to improve the "unconscious respawn wave" user experience.
* It may be a good idea to bake-in a mandatory period of AI deactivation whenever the object-scaling feature is enabled.  Placing AI on top of scaled objects usually results in dead AI because they fall through the object before the scaling takes effect.  If AI disabling is done as a part of this ticket, try to make it reusable for this purpose.

Separate tickets should be made for these side thoughts but I'm lazy - whoever takes on this ticket, remind me to make these side tickets before this one is closed.

### PR DESCRIPTION
**Pull request by Cre8or**
### Pull Request Description
**When merged this pull request will:**
- Introduce the `Ceasefire` component to the framework
- Remove the `SafeStart` and `SafeEnd` components

### Release Notes
The `SafeStart` component has not been functional for a prolonged time. Reverting it to a working state proved to be easy, but it quickly became apparent that the feature set was no longer sufficient for today's requirements. Furthermore, the `SafeEnd` component was identified as offering little to no additional functionalities over that of the `SafeStart` component, raising questions about its *raison-d'être*.

In order to address the above points, the `Ceasefire` component has been introduced, replacing its two predecessors. From a mission maker/Zeus perspective, the biggest change is that ceasefires are handled via a new module (found under `[CAFE3] Misc`), which can be used on demand.
During a ceasefire, players are made invincible and captive. Additionally, while their weapons are still operational, projectiles are removed upon firing. This prevents engagements between players and AI in *most* scenarios (however, it doesn't catch *every* possible use of lethal force).
For more advanced use cases, a matching configuration file has been added, enabling mission makers to customise the initial "safe start"-like ceasefire (or disable it entirely).

#

The following screenshots showcase this new component (aswell as its associated Zeus module) in action:

grafik
*A ceasefire during mission start.*

grafik
*The Ceasefire Zeus module.*

#

Resolves https://github.com/CombinedArmsGaming/CAFE3/issues/59.

## IMPORTANT

- [x] The Release Notes section below must be filled out appropriately to explain the changes made in this PR. This section will be used in Framework Changelogs.
- [x] If the contribution affects [the wiki](https://github.com/Bubbus/F3_CA_BUB/wiki), please include your changes in this pull request so the wiki is consistently updated.
- [x] [Contribution Guidelines](https://github.com/Bubbus/F3_CA_BUB/blob/release/contributing.md) are read, understood and applied.
- [x] Title of this PR uses our standard template `[Descriptor] - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by dgibso29** [comment]
Idea: Integrate this with endings. An `apply_ceasefire` variable in the ending config would do the trick. IMO it's an obvious QoL addition to save Zeus from forgetting. Should be on by default.

**Review by Bubbus — DISMISSED** [review]
Looks fine, works fine.  Thanks Cre, good work.

Only comment is that the white border around the ceasefire notification only appears on the bottom and right sides - looks a bit strange, given that the rest of the CAFE UI uses borderless transparent black backgrounds it may be best to remove the border.

Let's get the merge conflicts fixed and let's get this into `develop`.

**Review by Bubbus — DISMISSED** [review]

**Review by Bubbus — APPROVED** [review]
🤺

**Review by Joecuronium — APPROVED** [review]
Did not look but I approve

**Pull request merged**
